# Site settings
title: Christian Bruckmayer
email: christian@bruckmayer.net
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Christian Bruckmayer.
  Software Engineering, Open Source, openSUSE, Travelling
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bruckmayer.net" # the base hostname & protocol for your site

socials:
  - fa: fa-envelope
    url: mailto:christian@bruckmayer.net
  - fa: fa-twitter
    url: https://twitter.com/bruckmayer
  - fa: fa-github
    url: https://github.com/chrisbr/
  - fa: fa-linkedin
    url: https://de.linkedin.com/in/bruckmayer
  - fa: fa-xing
    url: https://www.xing.com/profile/Christian_Bruckmayer

# Build settings
markdown: kramdown
